# Generated by Django 6.0.4 on 2026-04-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_car_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manuel', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='Sedan', max_length=50),
            preserve_default=False,
        ),
    ]
