# Generated by Django 6.0.4 on 2026-04-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_brand_car_transmission_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='car_type',
        ),
    ]
