# Generated by Django 6.0.4 on 2026-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_notification_options_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
