# Generated by Django 6.0.4 on 2026-05-18 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
    ]
