# Generated by Django 6.0.4 on 2026-04-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='Manuel', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
