# Generated by Django 6.0.4 on 2026-05-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_car_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
