# Generated by Django 6.0.4 on 2026-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_car_discount_end_car_discount_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='discount_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
