# Generated by Django 6.0.4 on 2026-05-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_car_discount_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='discount_ends_at',
        ),
    ]
